#!/bin/bash

# DIO Platform - Final Setup and Test Script

echo "🎯 DIO Platform - Final Setup Script"
echo "=================================="
echo ""

echo "✅ All Docker files have been created and fixed!"
echo ""

echo "🔧 Issues Fixed:"
echo "   • Removed obsolete 'version' from docker-compose.yml"
echo "   • Fixed Dockerfile.frontend to use 'npm install'"
echo "   • Fixed .dockerignore files (was too aggressive)"
echo "   • Updated all scripts to use 'docker compose'"
echo ""

echo "📁 Files Ready:"
echo "   • docker-compose.yml (main orchestration)"
echo "   • Dockerfile.frontend (Next.js app)"
echo "   • Dockerfile (Python services)"
echo "   • requirements.txt (Python dependencies)"
echo "   • .dockerignore (proper build contexts)"
echo ""

echo "🚀 To Start DIO Platform:"
echo ""
echo "Step 1: Clean up any existing containers"
echo "   docker compose down -v --remove-orphans"
echo ""
echo "Step 2: Clean Docker cache"
echo "   docker system prune -f"
echo ""
echo "Step 3: Start development environment"
echo "   docker compose --profile mock up -d --build"
echo ""
echo "Step 4: Initialize database"
echo "   npm run db:push"
echo ""
echo "Step 5: Wait 30 seconds for services to start"
echo "   sleep 30"
echo ""
echo "Step 6: Check status"
echo "   docker compose ps"
echo ""
echo "Step 7: Check services"
echo "   curl http://localhost:8000/health"
echo "   curl http://localhost:3000"
echo ""

echo "🎯 To Test Attack Simulator:"
echo ""
echo "Step 1: Build attack simulator"
echo "   cd components/attack-simulator"
echo "   docker build -t dio-attack-simulator ."
echo "   cd ../.."
echo ""
echo "Step 2: Launch attack"
echo "   docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py cpu"
echo ""

echo "📊 Access Points:"
echo "   • Frontend Dashboard: http://localhost:3000"
echo "   • Nerve Center API: http://localhost:8000"
echo "   • API Documentation: http://localhost:8000/docs"
echo "   • Mesh Network: ws://localhost:4222"
echo ""

echo "🔍 Troubleshooting:"
echo ""
echo "If build fails:"
echo "   1. Check Docker is running: docker info"
echo "   2. Check available disk space: df -h"
echo "   3. Check network connectivity"
echo "   4. Try: docker compose build --no-cache"
echo ""

echo "If services don't start:"
echo "   1. Check logs: docker compose logs [service-name]"
echo "   2. Check ports: netstat -tulpn | grep :3000"
echo "   3. Check network: docker network ls"
echo "   4. Restart: docker compose restart"
echo ""

echo "If dashboard not working:"
echo "   1. Check frontend logs: docker compose logs frontend"
echo "   2. Check browser console (F12)"
echo "   3. Clear browser cache"
echo "   4. Try different browser"
echo ""

echo "📚 Documentation:"
echo "   • README.md - Project overview"
echo "   • DEPLOYMENT.md - Detailed deployment guide"
echo "   • PHASE1_USE_CASES.md - 5 POC use cases"
echo "   • ATTACK_SIMULATOR.md - Attack testing guide"
echo "   • TROUBLESHOOTING.md - Troubleshooting guide"
echo "   • QUICK_FIX.md - Quick fix guide"
echo ""

echo "🎮 Attack Simulator Commands:"
echo "   • CPU Attack: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py cpu"
echo "   • Memory Attack: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py memory"
echo "   • Network Attack: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py network"
echo "   • Process Attack: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py process"
echo "   • File Attack: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py file"
echo "   • Multi-Vector: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py multi"
echo "   • Lateral: docker run --rm --network dio-platform_dio-network dio-attack-simulator python main.py lateral"
echo "   • Interactive: docker run --rm -it --network dio-platform_dio-network dio-attack-simulator python main.py interactive"
echo ""

echo "✅ All components are now properly configured!"
echo "🎉 Your DIO Platform is ready for Phase 1 POC!"
echo ""

echo "🚀 Quick Start Commands:"
echo ""
echo "# Start everything"
echo "docker compose --profile mock up -d --build && npm run db:push"
echo ""
echo "# Check status"
echo "docker compose ps"
echo ""
echo "# View logs"
echo "docker compose logs -f"
echo ""
echo "# Stop everything"
echo "docker compose down"
echo ""

echo "📞 For support, check the documentation files or provide:"
echo "   • Operating system and version"
echo "   • Docker version: docker --version"
echo "   • Full error messages"
echo "   • Output of: docker compose logs"